save_path: ../data/LAI_FAPAR

tiles:
  T31UFT:
    west: 4.436120625114681
    south: 51.324523354307196
    east: 6.077757925298724
    north: 52.34135509678961
  T31UGS:
    west: 6.5
    south: 52.0
    east: 7.5
    north: 53.0
  T32UMT:
    west: 6.5
    south: 51.5
    east: 7.5
    north: 52.5
  T32ULT:
    west: 6.5
    south: 51.0
    east: 7.5
    north: 52.0

dates:
  - "2022-05-10"
  - "2022-05-11"
  - "2022-05-12"
  - "2022-05-13"
  - "2022-05-14"

products:
  LAI:
    collection: "TERRASCOPE_S2_LAI_V2"
    band: "LAI_10M"
  FAPAR:
    collection: "TERRASCOPE_S2_FAPAR_V2"
    band: "FAPAR_10M"

crs:
  target: "EPSG:32631"

scaling:
  LAI: 10000
  FAPAR: 10000

paths:
  province_shapefile: "../data/geo_boundaries/pv_2022.shp"
  output_dir: "../data/NPP_processed_inputs/"
  npp_output_dir: "../NPP_outputs/"

  LAI_UGT_path: "../data/NPP_inputs/CLMS_products/VI_20220510T104621_S2A_T31UGT-010m_V101_LAI_FIXED_Qgis.tif"
  LAI_UFT_path: "../data/NPP_inputs/CLMS_products/VI_20220510T104621_S2A_T31UFT-010m_V101_LAI_FIXED_Qgis.tif"
  FAPAR_UGT_path: "../data/NPP_inputs/CLMS_products/VI_20220510T104621_S2A_T31UGT-010m_V101_FAPAR_FIXED_Qgis.tif"
  FAPAR_UFT_path: "../data/NPP_inputs/CLMS_products/VI_20220510T104621_S2A_T31UFT-010m_V101_FAPAR_FIXED_Qgis.tif"

  temp_nc_path: "../data/NPP_inputs/Temps/single_level_2m_daily_mean_temp_2022_NL_ERA5.nc"
  ssrd_nc_path: "../data/NPP_inputs/Temps/hourly_srrd_may_2022_netherlands.nc"

  estk_full_path: "../data/NPP_inputs/ESTK_kaarten/NL_2022_10m.tif"

  conversion_table_path: "../data/conversion_tables/25-04-15_conversietabel_MODIS_ESTK_LUTable_voorlopig.xlsx"

products:
  LAI:
    tiles: ["${paths.LA I_UGT_path}", "${paths.LAI_UFT_path}"]
  FAPAR:
    tiles: ["${paths.FAPAR_UGT_path}", "${paths.FAPAR_UFT_path}"]

dates:
  - "2022-05-10"
  - "2022-05-11"
  - "2022-05-12"
  - "2022-05-13"
  - "2022-05-14"

npp:
  month_slice:
    start: "2022-05-01"
    end: "2022-05-31"

estk:
  clipped_path: "../data/NPP_processed_inputs/ESTK_Gelderland.tif"
  reprojected_path: "../data/NPP_processed_inputs/ESTK_Gelderland_32631.tif"

outputs:
  lai_merged: "../data/NPP_processed_inputs/output_LAI_UTM31N.tif"
  fapar_merged: "../data/NPP_processed_inputs/output_FAPAR_UTM31N.tif"
  temperature: "../data/NPP_processed_inputs/temperature_Gelderland.tif"
  ssrd: "../data/NPP_processed_inputs/ssrd_Gelderland.tif"
  npp: "../NPP_outputs/NPP_Gelderland_May2022.tif"
